import { ShieldAlert } from "lucide-react";

export default function DisclaimerPage() {
    return (
        <div className="min-h-screen bg-[#060A14] flex justify-center text-slate-200 p-6 md:p-12 font-sans relative overflow-hidden">
            {/* Radial Glow Background */}
            <div className="pointer-events-none absolute inset-0 z-0 flex justify-center items-center overflow-hidden">
                <div className="absolute top-[-20%] left-[-10%] w-[600px] h-[600px] bg-[#FF8C00] opacity-[0.05] blur-[120px] rounded-full" />
            </div>

            <div className="relative z-10 max-w-3xl w-full bg-[#0B1021] border border-slate-800 p-8 md:p-14 rounded-3xl mt-10 shadow-2xl h-fit flex flex-col items-center">
                <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-red-500/20 to-orange-500/20 shadow-[0_0_20px_rgba(255,140,0,0.1)] mb-6 border border-red-500/30">
                    <ShieldAlert className="h-8 w-8 text-red-500" />
                </div>
                
                <h1 className="text-3xl font-extrabold text-white mb-2 font-heading tracking-tight text-center">Medical Disclaimer — Arogya AI</h1>
                <p className="text-red-400 font-bold tracking-widest uppercase text-sm mb-6">IMPORTANT — PLEASE READ CAREFULLY</p>
                
                <div className="mb-8 p-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                    <p className="text-lg text-red-200 font-medium leading-relaxed text-center">
                        Arogya AI is an AI-powered informational tool and is NOT a substitute for professional medical diagnosis, treatment, or advice.
                    </p>
                </div>

                <div className="space-y-8 text-slate-400 font-medium text-left w-full">
                    <section>
                        <h2 className="text-xl text-white font-bold mb-3">1. NOT MEDICAL ADVICE</h2>
                        <p className="leading-relaxed">
                            All responses generated by Arogya AI are for informational purposes only. They do not constitute medical advice and should not be treated as such.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl text-white font-bold mb-3">2. CONSULT A REAL DOCTOR</h2>
                        <p className="leading-relaxed">
                            Always consult a certified, licensed doctor for any medical condition. Visit your nearest Primary Health Centre (PHC) for proper diagnosis.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl text-white font-bold mb-3">3. AI LIMITATIONS</h2>
                        <p className="leading-relaxed">
                            AI responses may be incomplete, inaccurate, or not applicable to your specific situation. Never delay seeking real medical help because of an AI response.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl text-red-400 font-bold mb-3">4. EMERGENCY SITUATIONS</h2>
                        <p className="leading-relaxed mb-4">
                            If you or someone near you is experiencing a life-threatening emergency:
                        </p>
                        <div className="bg-slate-900 border border-slate-700 rounded-xl p-6 text-center">
                            <p className="text-2xl font-bold text-white tracking-widest mb-1">CALL 108 IMMEDIATELY</p>
                            <p className="text-slate-500 text-sm">(National Ambulance Service — India)</p>
                        </div>
                        <p className="leading-relaxed mt-4 font-bold text-slate-300">
                            Do not rely on Arogya AI in emergencies.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl text-white font-bold mb-3">5. ABHA COMPLIANCE NOTE</h2>
                        <p className="leading-relaxed">
                            Arogya AI is designed to align with Ayushman Bharat Digital Mission (ABDM) principles but is not officially certified by NHA.
                        </p>
                    </section>
                </div>

                <div className="mt-12 w-full pt-8 border-t border-slate-800 text-center">
                    <p className="text-slate-500 font-medium">
                        The developers of Arogya AI accept no liability for any harm arising from use of this application.
                    </p>
                </div>
            </div>
        </div>
    );
}
